//
//  GrocerySections.swift
//  Chava_GroceryApp
//
//  Created by Chava,Rashmi on 4/12/22.
//

import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Pantry",items_Array:[GroceryItem(itemName:"Rice",itemImage:"Rice",itemInfo:"Rice is the seed of the grass species Oryza sativa (Asian rice) or less commonly Oryza glaberrima. The name wild rice is usually used for species of the genera Zizania and Porteresia, both wild and domesticated, although the term may also be used for primitive or uncultivated varieties of Oryza."), GroceryItem(itemName: "Cereal", itemImage: "Cereal", itemInfo: "A cereal is any grass cultivated for the edible components of its grain, composed of the endosperm, germ, and bran. The term may also refer to the resulting grain itself. Cereal grain crops are grown in greater quantities and provide more food energy"), GroceryItem(itemName: "Oatmeal", itemImage: "Oatmeal", itemInfo: "Oatmeal is a preparation of oats that have been de-husked, steamed, and flattened, or a coarse flour of hulled oat grains  that have either been milled or steel-cut. Ground oats are also called white oats. Steel-cut oats are known as coarse oatmeal, Irish oatmeal, or pinhead oats."), GroceryItem(itemName: "Dry fruit", itemImage: "Dryfruit", itemInfo: "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. Dried fruit has a long tradition of use dating back to the fourth millennium BC in Mesopotamia."), GroceryItem(itemName: "Peanut", itemImage: "Peanut", itemInfo: "The peanut also known as the groundnut,goober, pindar  or monkey nut , is a legume crop grown mainly for its edible seeds. It is widely grown in the tropics and subtropics, being important to both small and large commercial producers.")] )

let groceryitem2 = Grocery( section: "Fresh Produce", items_Array: [GroceryItem(itemName: "Coriander Leaves", itemImage: "Coriander leaves", itemInfo: "Coriander  is an annual herb in the family Apiaceae. It is also known as Chinese parsley, dhania, or cilantro All parts of the plant are edible, but the fresh leaves and the dried seeds (as a spice) are the parts most traditionally used in cooking."), GroceryItem(itemName: "Fenugreek Leaves", itemImage: "Fenugreek leaves", itemInfo: "Fenugreek is an annual plant in the family Fabaceae, with leaves consisting of three small obovate to oblong leaflets. It is cultivated worldwide as a semiarid crop. Its seeds and leaves are common ingredients in dishes from the Indian subcontinent."), GroceryItem(itemName: "Fruits", itemImage: "Fruits", itemInfo: "A fruit is the seed-bearing structure in flowering plants that is formed from the ovary after flowering. Fruits are the means by which flowering plants disseminate their seeds. Edible fruits in particular have long propagated using the movements of humans and animals in a symbiotic relationship that is the means for seed dispersal for the one group and nutrition for the other."), GroceryItem(itemName: "Spinach", itemImage: "Spinach", itemInfo: "Spinach is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh, or after storage using preservation techniques by canning, freezing, or dehydration."), GroceryItem(itemName: "Vegetables", itemImage: "Vegetables", itemInfo: "Vegetables are parts of plants that are consumed by humans or other animals as food. The original meaning is still commonly used and is applied to plants collectively to refer to all edible plant matter, including the flowers, fruits, stems, leaves, roots, and seeds.")] )

let groceryitem3 = Grocery( section: "Seafood", items_Array: [GroceryItem(itemName: "Crab", itemImage: "Crab", itemInfo: "Crabs are decapod crustaceans of the infraorder Brachyura, which typically have a very short projecting tail, usually hidden entirely under the thorax. They live in all the world's oceans, in fresh water, and on land, are generally covered with a thick exoskeleton, and have a single pair of pincers. They first appeared during the Jurassic Period."), GroceryItem(itemName: "Fish", itemImage: "Fish", itemInfo: "Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits. Included in this definition are the living hagfish, lampreys, and cartilaginous and bony fish as well as various extinct related groups. Around 99% of living fish species are ray-finned fish, belonging to the class Actinopterygii, with over 95% belonging to the teleost subgrouping."), GroceryItem(itemName: "Lobster", itemImage: "Lobster", itemInfo: "Lobsters are a family of large marine crustaceans. Lobsters have long bodies with muscular tails, and live in crevices or burrows on the sea floor. Three of their five pairs of legs have claws, including the first pair, which are usually much larger than the others."), GroceryItem(itemName: "Mussel", itemImage: "Mussel", itemInfo: "Mussel is the common name used for members of several families of bivalve molluscs, from saltwater and freshwater habitats. These groups have in common a shell whose outline is elongated and asymmetrical compared with other edible clams, which are often more or less rounded or oval.The word mussel is frequently used to mean the bivalves of the marine family Mytilidae."), GroceryItem(itemName: "Prawn", itemImage: "Prawn", itemInfo: "Prawn is a common name for small aquatic crustaceans with an exoskeleton and ten legs, some of which can be eaten. The terms shrimp and prawn are common names, not scientific names. They are vernacular or colloquial terms which lack the formal definition of scientific terms. They are not taxa, but are terms of convenience with little circumscriptional significance")] )

let groceryitem4 = Grocery( section: "Beverages", items_Array: [GroceryItem(itemName: "Water", itemImage: "Water", itemInfo: "Water is the most popular drink in the world. This is such a simple beverage, and yet no one can survive without it. This is why people have invented different water treatment systems, to ensure everyone around the world can have clean and safe water to drink."), GroceryItem(itemName: "Tea", itemImage: "Tea", itemInfo: "After water, tea is the most popular drink in the world. Tea is made by pouring hot water over cured tea leaves. This popular beverage can be enjoyed hot or cold, and can bring different health benefits. Tea plants mostly grow in Asia, but tea is enjoyed in many countries around the world."), GroceryItem(itemName: "Coffee", itemImage: "Coffee", itemInfo: "Coffee beans are produced in at least 70 countries around the world, and many people drink coffee several times a day. It is mostly enjoyed hot, but iced coffee is also very popular, especially in the summer. Just like tea leaves, coffee beans come from an evergreen shrub."), GroceryItem(itemName: "Hot Chocolate", itemImage: "Hot chocolate", itemInfo: "Hot chocolate, also known as hot cocoa or drinking chocolate, is heated chocolate milk. Hot chocolate made with melted chocolate is sometimes called drinking chocolate, characterized by less sweetness and a thicker consistency."), GroceryItem(itemName: "Soft Drink", itemImage: "Soft drink", itemInfo: "A soft drink is a drink that usually contains water, a sweetener, and a natural and/or artificial flavoring. The sweetener may be a sugar, high-fructose corn syrup, fruit juice, a sugar substitute or some combination of these. Soft drinks may also contain caffeine, colorings, preservatives, and/or other ingredients.")] )

let groceryitem5 = Grocery( section: "Frozen", items_Array: [GroceryItem(itemName: "Fish Fillet", itemImage: "Fish fillet", itemInfo: "A fish fillet, from the French word filet meaning a thread or strip,is the flesh of a fish which has been cut or sliced away from the bone by cutting lengthwise along one side of the fish parallel to the backbone. In preparation for filleting, any scales on the fish should be removed. The contents of the stomach also need careful detaching from the fillet."), GroceryItem(itemName: "Peas", itemImage: "Peas", itemInfo: "The pea is most commonly the small spherical seed or the seed-pod of the pod fruit Pisum sativum. Each pod contains several peas, which can be green or yellow. Botanically, pea pods are fruit, since they contain seeds and develop from the ovary of a (pea) flower. "), GroceryItem(itemName: "Fish Finger", itemImage: "Fish finger", itemInfo: "Fish fingers or fish sticks are a processed food made using a whitefish, such as cod, hake, haddock or pollock, which has been battered or breaded. They are commonly available in the frozen food section of supermarkets. They can be baked in an oven, grilled, shallow fried, or deep-fried."), GroceryItem(itemName: "Pizza", itemImage: "Pizza", itemInfo: "Pizza is a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients which is then baked at a high temperature, traditionally in a wood-fired oven. A small pizza is sometimes called a pizzetta. A person who makes pizza is known as a pizzaiolo."), GroceryItem(itemName: "Sausage", itemImage: "Sausage", itemInfo: "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]

